<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url('manage/default', array('controller' => 'UnderSubject','action' => 'index')).
                '?x=1&page='.$this->previous.
                '&column='.$this->column.
                '&parame='.$this->parame;?>">
                < 前一页
            </a> |
        <?php else: ?>
            <span class="disabled">< 前一页</span> |
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url('manage/default', array('controller' => 'UnderSubject','action' => 'index')).
                    '?x=1&page='.$page.
                    '&column='.$this->column.
                    '&parame='.$this->parame;?>">
                    <?php echo $page; ?>
                </a> |
            <?php else: ?>
                <?php echo $page; ?> |
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url('manage/default', array('controller' => 'UnderSubject','action' => 'index')).
                '?x=1&page='.$this->next.
                '&column='.$this->column.
                '&parame='.$this->parame;?>">
                下一页 >
            </a>
        <?php else: ?>
            <span class="disabled">下一页 ></span>
        <?php endif; ?>
    </div>
<?php endif; ?>