<?php
/**
 * @author cry
 * @function: 学生补充信息  文件凭证电子材料上传表单
 */
namespace Stu\Form;

use Zend\Form\Element;
use Zend\Form\Form;

use Zend\InputFilter\InputFilter;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;
use Zend\InputFilter\InputFilterProviderInterface;

use Zend\Validator\File\Extension;
use Zend\Validator\File\Size;
use Zend\Validator\File\ImageSize;
use Zend\Validator\File\MimeType;
use Zend\Filter\File\Rename;
use Zend\Session\Container;


class EinfoForm extends Form implements InputFilterProviderInterface{

//    private $uid;
    private $id;
    private $einfoArr;
    private $num;
    public $inputFilter;

    public function __construct($einfoArr){
//        $this->einfoArr = (array)$einfoArr;

        parent::__construct('stu_einfo_form');
//        $uploadclass = "span4";
//        $this->uid =$uid;//取当前用户的uid

        //给表添加元素
//        $this->add(array(//uname Text
//            'name' => 'uid',
//            'type' => 'Hidden',
//            'options' => array(
//                'label' => '用户编号',
//            ),
//            'attributes'=>array(
//                'value'=>$this->uid,
//            )
//        ));
        if( is_array($einfoArr) ){
            foreach ($einfoArr as $row){
                $maxnum = $row->maxnum;
                for( $i = 1 ; $i <= $maxnum ; $i++ ){
                    $this->add(array(
                        'name' => 'einfo_' . $row->id."_".$i,
                        'type' => 'File',
                        'options'=>array(
                            'label'=>$row->name ,

                        ),
                        'attributes' => array(
                            'id' => 'einfo_' . $row->id."_".$i,
                            'accept' => '.png,.jpeg,image/png, image/jpeg, image/jpg,application/pdf',
                            'onchange ' => 'limit_filesize(this)',
                        ),
                    ));//$this->add
                }
            }
        }

        //提交按钮
        $this->add(array(//save Submit
            'name'=>'save',
            'type'=>'button',
            'attributes'=>array(
                'value'=>'上传文件',
                'id'=>'save',
                'class'=>'btn btn-primary',
            ),
        ));
    }
    public function getInputFilter()
    {

        return parent::getInputFilter(); // TODO: Change the autogenerated stub
    }

    public function getInputFilterSpecification()
    {
    }
}