<?php
use Zend\Session\Container;
echo $this->doctype();
?>

<style>
    label span, label {
        text-align: left;
        margin-right: 30px;
        height: 35px;
    }

    input[type="text"] {
        height: 20px;
        width: 140px;
        margin-bottom: 0;
    }

    select {
        height: 30px;
        width: 150px;
        margin-bottom: 0;
    }

    label {
        font-size: 15px;
        text-align: center;
        width: 150px;
        margin-right: 10px;
    }
    .message1{
        color: #EE0000;
    }
    .message2{
        color:  #A9A9A9;
    }
</style>
<?php
//$title = '用户管理';
//$this->headTitle($title);
//?>
<!--<h1>--><?php //echo $this->escapeHtml($title); ?><!--</h1>-->
<ul id='myTab' class='nav nav-tabs' style='margin-top: 20px;'>
    <?php
    echo "<li class='active'><a href='".$this->url("manage/default",array("controller"=>"systemManagement","action"=>"addUser"))."' >新增用户</a></li>";
    echo "<li><a href='".$this->url("manage/default",array("controller"=>"systemManagement","action"=>"others"))."' >管理其他用户</a></li>";
    ?>
</ul>


<!--<ul class="nav nav-tabs">-->
<!--    <li class="active">-->
<!--        <a href="#add" data-toggle="tab" id="add" style="background-color: #fff">-->
<!--            新增用户-->
<!--        </a>-->
<!--    </li>-->
<!--    <li>-->
<!--        <a href="#other" data-toggle="tab" id="other">-->
<!--            管理其他用户-->
<!--        </a>-->
<!--    </li>-->
<!--</ul>-->

<!--<p style='color:red'>创建用户时，用户名请填写老师的邮箱，并将老师的工号作为密码</p>-->
<div id="add">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('manage/default',array('controller'=>'systemManagement','action'=>'addUser')));
    $form->setAttribute('method','POST');
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
</div>

<?php
    $rid_arr_container = new Container('rid');
    $rid_arr = $rid_arr_container->item;
    if (in_array(10, $rid_arr)){
        echo '<a class="btn btn-primary" id="addNewArticle" href="/college/otherOperation/loadData">excel文件一键导入</a>';
        echo '<p ><span style="color: #A9A9A9;">注：点击此处可以通过excel导入学院及用户信息</span></p>';
    }
?>
<!--<a class="btn btn-primary" id="addNewArticle" href="/college/otherOperation/loadData">excel文件一键导入</a>-->
<!--<p ><span style="color: #A9A9A9;">注：点击此处可以通过excel导入学院及用户信息</span></p>-->
<!--<br>-->
<!--<br>-->



<!--    echo $this->form()->openTag($form);-->
<!--    echo $this->formHidden($form->get('Uid'));-->
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Uname')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Uname')); ?></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Password')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Password')); ?></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Password2')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Password2')); ?><span class = 'message2'>&nbsp;&nbsp;&nbsp;&nbsp;</span></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Realname')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Realname')); ?><span class = 'message2'>&nbsp;&nbsp;&nbsp;&nbsp;</span></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Mobile')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Mobile')); ?></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Email')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Email')); ?></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('Rid')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('Rid')); ?></div>
</div>
<br>
<div class="row">
    <div class="span3"><?php echo $this->formLabel($form->get('YXSM')); ?></div>
    <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form->get('YXSM')); ?></div>
</div>
<div class="row">
    <div class="span7" style="text-align: center;"><?php echo $this->formElement($form->get('submit')); ?></div>
</div>
<br>
<?php   echo $this->form()->closeTag();
?>
<?php
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">用户名</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Uname'))."</div>";
//    echo "<span class=\"help-block\">请使用邮箱账号</span>";
//    echo "<div><p color=\"color:red\"><span id=\"warning\"> </span></p></div>";
//    echo "</div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">密码</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Password'))."</div>";
//    echo "<span class=\"help-block\">6-24个数字或字符</span>";
//    echo "</div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">确认密码</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Password2'))."</div></div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">真实姓名</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Realname'))."</div></div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">移动电话</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Mobile'))."</div></div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">电子邮箱</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Email'))."</div></div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">角色</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('Rid'))."</div></div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<label for=\"firstname\" class=\"col-sm-2 control-label\">院系所</label>";
//    echo "<div class=\"col-sm-4\">".$this->formRow($form->get('YXSM'))."</div></div>";
//
//    echo "<div class=\"form-group\">";
//    echo "<div class=\"col-sm-offset-2 col-sm-5\">";
//    echo $this->formSubmit($form->get('submit'))."</div></div>";
//
//    echo $this->form()->closeTag();
//    ?>
<?php
if($this->msg)
    echo "<script>alert('".$this->msg."');</script>";
?>
<script type="application/javascript">
    $("#other").click(function () {
        window.location.replace("<?php echo $this->url('manage/default',array('controller'=>'systemmanagement','action' => 'others')); ?>");
    });
</script>