<?php
$title = '添加学院信息';
$this->headTitle($title);
?>
<!--<h3><?php echo $this->escapeHtml($title);?></h3>-->
<style type="text/css">
    .message{
        color: #b23131;
    }
</style>
<!--  提交审核按钮 -->
<!--<br><br>-->
<?php
//if(in_array(1,$this->rid)){
//    echo " <a href = '".$this->url("manage/addCollege",array("controller"=>"system-management","action"=>"add-college"))."' onclick='javascript:return ifCheck()' class='btn btn-danger'>提交审核</a>";
//}
//?>
<!--<br/>-->
<!--<input id="confirmcheck" type="button" onclick="javascript:return ifCheck()" class="btn" value=" 提交审核 ">-->
<!---<a href = '<?php echo $this->url("manage/addCollege",array("controller"=>"system-management","action"=>"add-college")); ?>' onclick='javascript:return ifCheck()' class='btn btn-danger'>提交审核</a>
<br/><br/>
----->
<br>
<!--<div class = "tab-content" >-->
<!-- ******************** Tab1 学院信息填写 ******************** -->
<div class = "tab-pane active" id = "addinfo2" >
    <!--<h3>添加科研或实践项目经历</h3>-->
    <form class="form-horizontal"  action="/manage/system-manage/addCollege/uid/<?php echo $this->uid?>" method="post" enctype="multipart/form-data">
        <div class="control-group">
            <label class="control-label" for="college_id">学院编号</label>
            <div class = "controls">
                <span class = 'message'>*&nbsp;</span>
                <textarea   rows="1" id="college_id" name="college_id" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="college_name">学院名称</label>
            <div class = "controls">
                <textarea   rows="1" id="college_name" name="college_name" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="college_id">学院电话</label>
            <div class = "controls">
                <textarea   rows="1" id="phone" name="phone" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="college_id">网址</label>
            <div class = "controls">
                <textarea   rows="1" id="ip_address" name="ip_address" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="college_id">办公楼地址</label>
            <div class = "controls">
                <textarea   rows="1" id="address" name="address" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
                <div class='text-right'>
                    <em style='color:red'>50</em>/<span>50</span>字符
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="button" id="add_college" class="btn btn-primary"> 确认添加学院 </button>
            </div>
        </div>
    </form>


    <div class="span12">
        <?php if($this->college_table){
            ?>
            <h3>已添加的学院信息</h3>
            <table class='table table-striped table-hover table-condensed'>
                <thead>
                <th>编号</th>
                <th>名称</th>
                <th>联系电话</th>
                <th>办公地址</th>
                <th>网址</th>
                <th>操作</th>
                </thead>
                <tbody>
                <?php
                foreach ($this->college_table as $key => $row) {
                    ?>
                    <tr>

                        <td class="span2"> <?php echo $row->college_id;?></td>
                        <td class="span3"> <?php echo $row->college_name;?></td>
                        <td class="span3"> <?php echo $row->phone;?></td>
                        <td class="span3"> <?php echo $row->ip_address;?></td>
                        <td  class="span2"><?php echo $row->address;?></td>
                        <td  class="span2">
                            <!--<?php echo $row->project_id;?>-->
                            <a href='<?php echo $this->url("manage/addCollege",array("controller"=>"system-management","action"=>"add-college","id"=>$row->college_id)); ?>'  onclick='javascript:return ifCheckdel()' class="button">删除  </a>
                            <a href='<?php echo $this->url("manage/addCollege",array("controller"=>"system-management","action"=>"add-college","id"=>$row->college_id)); ?>'  onclick='javascript:return ifCheckdel()' class="button">编辑  </a>
                        </td>
                    </tr>
                <?php } ?> <!-- 循环输出项目记录-->
                </tbody>
            </table>
        <?php  } ?>
    </div>


</div>
<!--</div>-->
<script type="text/javascript" src="<?php echo $this->basePath('js/stu/stuconfirm.js?version=1.1.1');?>"></script>
<script>
    /*
     * 判断是否为全角
     *
     * pChar:长度为1的字符串
     * return: true:全角
     *         false:半角
     */
    function isFull (pChar){
        if((pChar.charCodeAt(0) > 128)){return true;}
        else{return false;}
    }


    $(document).ready(function(){

        $("#add_project").click(function () {
            var college_id = $("#college_id").val();
            var college_name = $("college_name").val();
            var phone = $("#phone").val();
            var ip_address = $("#ip_address").val();
            var address =$("address").val();
            // alert(file+ '/' +certificate.name + '/' + certificate.type + '/' + certificate.size);
            if(!college_id){
                alert("项目名称不可以为空！");
                $("#college_id").focus();
            } else if(!college_name){
                alert("项目概要不可以为空！");
                $("#college_name").focus();
            }else if(!phone){
                alert("项目结论不可以为空！");
                $("#phone").focus();
            }else if(!ip_address){
                alert("项目成果不可以为空！");
                $("#ip_address").focus();
            }else if(!address){
                alert("请选择项目级别！");
                $("#address").focus();
            }else{
                $(this).prop("type","submit");
            }
        })
    });

</script>