<style>
    label span, label {
        text-align: left;
        margin-right: 40px;
        height: 35px;
    }

    input[type="text"] {
        height: 30px;
        width: 150px;
        margin-bottom: 0;
    }

    input[type="datetime"] {
        height: 30px;
        width: 150px;
        margin-bottom: 0;
    }

    input[type="select"] {
        height: 30px;
        width: 150px;
        margin-bottom: 0;
    }

    select {
        height: 30px;
        width: 150px;
        margin-bottom: 0;
    }

    label {
        margin-right: 40px;
    }
    .message1{
        color: #EE0000;
    }

    .message2{
        color:  #A9A9A9;
    }
    #myEditModal{
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
<!--<script type="text/javascript">-->
<!--    function getindex()-->
<!--    {-->
<!---->
<!--        var obj = event.srcElement;-->
<!--        var trobj = obj.parentElement.parentElement;-->
<!--        var tbobj = trobj.parentElement;-->
<!--        //var url = window.location.href;-->
<!--        var index = trobj.rowIndex-1;-->
<!--        var id = parseInt(document.getElementById("id").innerText)+parseInt(index);-->
<!--        var add = "http://211.71.149.244:11111/manage/systemManagement/edit/param1/"+id;-->
<!--        //alert(url);-->
<!--        //window.location.replace(add);-->
<!--        //window.location.href=add;-->
<!---->
<!--        var url = window.location.protocol + "//"+window.location.host;-->
<!--        if(window.location.port){-->
<!--            url = url +":"+ post;-->
<!--        }-->
<!--        url = url+"/manage/systemManagement/others/param1/"+id;-->
<!--        //http://tm59/stu/register/register-->
<!--        alert(url);-->
<!--        window.location.replace(url);-->
<!---->
<!--    }-->
<!--</script>-->

<?php
//$title = '用户管理';
//$this->headTitle($title);
//?>
<!--<h1>--><?php //echo $this->escapeHtml($title); ?><!--</h1>-->
<ul id='myTab' class='nav nav-tabs' style='margin-top: 20px;'>
    <?php
    echo "<li><a href='".$this->url("manage/default",array("controller"=>"systemManagement","action"=>"addUser"))."' >新增用户</a></li>";
    echo "<li class='active'><a href='".$this->url("manage/default",array("controller"=>"systemManagement","action"=>"others"))."' >管理其他用户</a></li>";
    ?>
</ul>

<!--<h3>已设项</h3>-->
<?php
function object_to_array($obj) {
    $obj = (array)$obj;
    foreach ($obj as $k => $v) {
        if (gettype($v) == 'resource') {
            return;
        }
        if (gettype($v) == 'object' || gettype($v) == 'array') {
            $obj[$k] = (array)object_to_array($v);
        }
    }
    return $obj;
}

if(isset($this->teacher)){
echo "<table class='table table-hover'>";
echo "<tr>";
foreach ($this->column as $key => $value){
    echo "<th>$value</th>";
}
echo "</tr>";
foreach ($this->teacher as $timer){
//var_dump($univer);
$uniarr = object_to_array($timer);
$aaa=json_encode($uniarr);
$str = 'editform('.$aaa.')';
//echo $str;
foreach ($this->column as $key => $value){

if ($key == 'id')
echo "<td id='id'>".$uniarr[$key]."</td>";
//            else if($key == 'status')
//            {
//                if ($uniarr[$key] == -1) {
//                    echo "<td>关</td>";
//                }
//                else {
//                    echo "<td>开</td>";
//                }
//            }
//            else if ($key == 'sta') {
//                if ($uniarr[$key] == 0) {
//                    echo "<td>已截止</td>";
//                }
//                else {
//                    echo "<td>进行中</td>";
//                }
//            }
else if ($key == 'oprat')
{
$id = 'staff_id';
//echo "id---------------------->".$id;
echo "<td><button type='button' class='btn btn-primary' id='btn' data-toggle='modal' data-target='#myEditModal' onclick='".$str."'>编辑</button></td>";
?>
<td><button type='button' class="btn btn-danger"><a style="color: white" href="<?php echo $this->url('manage/default',array('controller'=>'SystemManagement','action'=>'deleteUser','uid' => $uniarr[$id]));?>" onclick="return confirm('确认删除吗?')">删除</a></button>&nbsp;&nbsp;&nbsp;&nbsp;
    <?php
    }
    else
        echo "<td>".$uniarr[$key]."</td>";
    }
    echo "</tr>";
    }
    echo "</table>";
    }
    $url_arr = '/manage/systemManagement/others/param1/';
    if(isset($url_arr)){
        $get_param = "";
        for($i=1;$i<=5;$i++){
            if(isset($url_arr['param'.$i])){
                $get_param .= "/param".$i."/".$url_arr['param'.$i];//$url_arr['param'.$i];
            }
        }
    }
    $url = '/manage/systemManagement/others/param1/';
    if ($this->pageCount):
        ?>

        <div class="paginationControl">
            <!-- Previous page link -->
            共计<?php echo $this->total_num?$this->total_num:0 ;?>条数据
            <?php if (isset($this->previous)): ?>
                <a href="<?php echo $url. $this->previous .$get_param; ?>">
                    < 上一页
                </a> |
            <?php else: ?>
                <span class="disabled">< 上一页</span> |
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <a href="<?php echo $url. $page .$get_param;?>">

                        <?php echo $page; ?>
                    </a> |
                <?php else: ?>
                    <?php echo $page; ?> |
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <a href="<?php echo $url. $this->next; ?>">
                    下一页 >
                </a>
            <?php else: ?>
                <span class="disabled">下一页 ></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <div class="modal fade" id="myEditModal" tabindex=-1  aria-lablledby="myEditModalLabel" role="dialog" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="myEditModalLabel">修改用户信息</h3>
                </div>
                <div class="modal-body">
                    <?php
                    $form1 = $this->form1;
                    $form1->setAttribute('action',$this->url('manage/default',array('controller'=>'systemManagement','action'=>'others')));
                    $form1->setAttribute('method','POST');
                    $form1->prepare();

                    echo $this->form()->openTag($form1);?>
                    <div class="row">
                        <div class="span4"><?php echo $this->formLabel($form1->get('Staffid')); ?></div>
                        <div class="span7" readonly="true" disabled="true"><?php echo $this->formElement($form1->get('Staffid')); ?></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="span4"><?php echo $this->formLabel($form1->get('Uname')); ?></div>
                        <div class="span7" readonly="true" disabled="true"><?php echo $this->formElement($form1->get('Uname')); ?></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="span4"><?php echo $this->formLabel($form1->get('Realname')); ?></div>
                        <div class="span7" readonly="true" disabled="true"><?php echo $this->formElement($form1->get('Realname')); ?></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="span4"><?php echo $this->formLabel($form1->get('Rid')); ?></div>
                        <div class="span7"><span class = 'message1'>*</span><?php echo $this->formElement($form1->get('Rid')); ?></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="span12"><span class = 'message1'>点击确定将会删除该用户的所有权限并重新授予用户权限，请慎重考虑</span></div>
                    </div>
                </div>
                <div class="modal-footer" >
                    <button type="submit" class="btn btn-primary" id="confirmEdit" >确定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <?php
                    $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>

    <script type="application/javascript">
        //编辑学生成绩
        function editform(item) {
            //去掉名字中间的空格
            //var item=JSON.stringify(items);
            //alert(item.name);
            $("#Staffid").attr('value',item.staff_id);
            $("#Uname").attr('value',item.user_name);
            $("#Realname").attr('value',item.real_name);
            $("#confirmEdit").click(function()
            {
                $.post('manage/SystemManagement/others',function()
                {
                    //location.reload();
                });
            });
            //s$("#myEditModal").modal('toggle');
        }
    </script>

