<?php
    $title = '推免生注册补充信息';
    $this->headTitle($title);
?>
<!--<h3><?php echo $this->escapeHtml($title);?></h3>-->
<style type="text/css">
    .message{
        color: #b23131;
    }
</style>

<!--  提交审核按钮 -->
<br><br>
<div class='message'>
    提示1. 请在补充完个人全部信息【基本信息(含必填项)、科研经历(选填)、个人奖励含优秀营员(选填)、文件凭证(含必须上传的项)】后再提交审核。<br/>
    提示2. 在提交审核之前，您的所填信息可随意更改。<br/>
    提示3. 请在要求的提交审核期限内提交。<br/>
    <br/>
</div>

<!--<input id="confirmcheck" type="button" onclick="javascript:return ifCheck()" class="btn" value=" 提交审核 ">-->
<?php
if(in_array(1,$this->rid)){
   echo " <a href = '".$this->url("stu/default",array("controller"=>"addinfo","action"=>"stuConfirmcheck"))."' onclick='javascript:return ifCheck()' class='btn btn-danger'>提交审核</a>";
}
?>
<br/>

<ul class = "nav nav-tabs" id = "myTab" >
    <li class="active"> <a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfo","uid" => $this->uid)); ?>'>基本信息</a></li>
    <li><a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfoProject","uid" => $this->uid)); ?>'>科研经历</a></li>
    <li><a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfoHonour","uid" => $this->uid)); ?>' > 个人奖励（含优秀营员） </a></li>
    <li><a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfoFile","uid" => $this->uid)); ?>'> 文件凭证 </a></li>
</ul>
<br/>
<div class = "tab-content" >
    <!-- ******************** Tab1 基本信息 ******************** -->
    <div class = "tab-pane active" id = "addinfo1" >

        <!--学生注册信息显示-->
        <h3>注册信息显示</h3>
        <table class='table table-striped table-hover table-condensed'>
            <thead>
                <th>姓名</th>
                <th>申请类型</th>
                <th>性别</th>
                <th>身份证号</th>
                <th>民族</th>
                <th>政治面貌</th>
                <th>联系方式</th>
                <th>电子邮箱</th>
                <th>英语四级成绩</th>
                <th>本科高校</th>
            </thead>


            <tbody>
            <tr>
                <td><?php  echo $this->stu_register_info['user_name']?></td>
                <td><?php  echo $this->stu_register_info['apply_type']?></td>
                <td><?php  echo $this->stu_register_info['gender']?></td>
                <td><?php  echo $this->stu_register_info['idcard']?></td>
                <td><?php  echo $this->stu_register_info['nationality']?></td>
                <td><?php  echo $this->stu_register_info['political_status']?></td>
                <td><?php  echo $this->stu_register_info['phone']?></td>
                <td><?php  echo $this->stu_register_info['email']?></td>
                <td><?php  echo $this->stu_register_info['value_cet4']?></td>
                <td><?php  echo $this->stu_register_info['graduate_university']?></td>
            </tr>
            </tbody>
        </table>
        <br><hr>

        <!--基础信息添加的表单-->
        <h3>基本信息填写、修改及显示</h3>
        <?php
            $this->form->setAttribute('action',$this->url('stu/default',array('controller'=>'addinfo','action'=>'addInfo',"uid" => $this->uid)));
            $this->form->setAttribute('method','POST');
            $this->form->prepare();
            echo $this->form()->openTag($this->form);
        ?>
        <!-- 1.1 本科院系（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('graduate_college')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('graduate_college')); ?></div>
        </div>
        <br>
        <!-- 1.2 本科学科门类（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('graduate_subject')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('graduate_subject')); ?></div>
        </div>
        <br>
        <!-- 1.3 本科专业类（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('graduate_professional_class')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('graduate_professional_class')); ?></div>
        </div>
        <br>
        <!-- 1.4 本科专业（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('graduate_profession')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('graduate_profession')); ?></div>
        </div>
        <br>
        <!-- 1.5 本专业同年级人数（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('pro_stu_num')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('pro_stu_num')); ?></div>
        </div>
        <br>
        <!-- 1.6 本专业排名（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('ranking')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('ranking')); ?></div>
        </div>
        <br>
        <!-- 1.7 本科绩点（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('grade_point')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('grade_point')); ?></div>
        </div>
        <br>
        <!-- 1.8 CET6英语六级成绩（选填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('value_cet6')); ?></div>
            <div class="span7">&nbsp;&nbsp;<?php echo $this->formElement($form->get('value_cet6')); ?></div>
        </div>
        <br>
        <hr>
        <!-- 1.9 目标高校（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('target_university')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('target_university')); ?></div>
        </div>
        <br>
        <!--1.10 目标院系(必填)-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('target_college')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('target_college')); ?></div>
        </div>
        <br>
        <!-- 1.11 目标专业（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('target_subject')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('target_subject')); ?></div>
        </div>
        <br>
        <!-- 1.12 目标方向（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('target_profession')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('target_profession')); ?></div>
        </div>
        <br>
        <!-- 1.13 意向导师（选填）请选择一志愿-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('target_professor')); ?></div>
            <div class="span9">
                <span class = 'message'>*&nbsp;</span>
                <?php echo $this->formElement($form->get('target_professor')); ?>
                <?php echo $this->formElement($form->get('target_professor2')); ?>
                <?php echo $this->formElement($form->get('target_professor3')); ?>
            </div>
        </div>
        <br>
        <hr>
        <!-- 1.14 外语语种（必填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('foreign_language')); ?></div>
            <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('foreign_language')); ?></div>
        </div>
        <br>
        <!-- 1.14  GRE成绩（选填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('gre_score')); ?></div>
            <div class="span7">&nbsp;&nbsp;<?php echo $this->formElement($form->get('gre_score')); ?></div>
        </div>
        <br>
        <!--  1.15 TOEFL成绩（选填）-->
        <div class="row">
            <div class="span3"><?php echo $this->formLabel($form->get('toefl_score')); ?></div>
            <div class="span7">&nbsp;&nbsp;<?php echo $this->formElement($form->get('toefl_score')); ?></div>
        </div>
        <br>

        <div class="row">
            <div class="span4"></div>
            <?php echo $this->formSubmit($form->get('addinfo_submit'));  ?>
        </div>
        <?php  echo $this->form()->closeTag();?>
        <!--<input type="hidden"  id ="graduate_professional_class_hidden" value = <?php echo $this->stubase['graduate_professional_class'] ?> >;-->
        <!--<input type="hidden"  id ="graduate_profession_hidden" value='<?php  ?>' >;-->

        <!--<input type="hidden"  id ="target_subject_hidden" value='<?php  ?>' >;-->
        <!--<input type="hidden"  id ="target_profession_hidden" value='<?php  ?>' >;-->
        <!--<input type="hidden"  id ="target_professor_hidden"  value='<?php  ?>' >;-->
        <!--<input type="hidden"  id ="target_professor2_hidden"  value='<?php  ?>' >;-->
        <!--<input type="hidden"  id ="target_professor3_hidden"  value='<?php  ?>' >;-->
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('js/stu/stuinfo.js?version=1.1.1');?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/stu/stuconfirm.js?version=1.1.1');?>"></script>
<!--<script>-->
    <!--function ifCheck(){-->
        <!--var msg ="您确认提交么？";-->
        <!--if(confirm(msg)==true){-->
            <!--// alert("提交进行中...");-->
            <!--return true;-->
        <!--}else{-->
            <!--// alert("取消提交ing...");-->
            <!--return false;-->
        <!--}-->

    <!--}-->
<!--</script>-->
<script>
    $(document).ready(function(){
        // $('#myTab a:first').tab('show')
        // $( '#myTab a' ). click ( function ( e ) {//Tab切换
        //     e.preventDefault();
        //     $(this).tab('show');
        // })

        $("#addinfo_submit").click(function (){
            var graduate_subject = $("#graduate_subject").val();//本科院系（必填）
            var graduate_college = $("#graduate_college").val();//本科学科门类（必填）
            var graduate_professional_class = $("#graduate_professional_class").val();//本科专业类（必填）
            var graduate_profession = $("#graduate_profession").val();//本科专业（必填）
            var pro_stu_num  = $("#pro_stu_num").val();//本专业同年级人数（必填）
            var ranking  = $("#ranking").val();//本专业排名（必填）
            var grade_point = $("#grade_point").val();//本科绩点（必填）
            var value_cet6 = $("#value_cet6").val();//英语六级成绩（选填）
            var target_university = $("#target_university").val();//目标高校（必填）：北京林业大学
            var target_college = $("#target_college").val();//目标院系（必填）
            var target_subject = $("#target_subject").val();//目标专业（必填）
            var target_profession = $("#target_profession").val();//目标方向（必填）
            var target_professor = $("#target_professor").val();//意向导师（选填）
            var target_professor2 = $("#target_professor2").val();
            var target_professor3 = $("#target_professor3").val();
            var foreign_language = $("#foreign_language").val();//外语语种（必填）
            var gre_score = $("#gre_score").val();//GRE成绩（选填）
            var toefl_score = $("#toefl_score").val();//TOEFL成绩（选填）

            if( !graduate_subject ){
                alert("本科院系未填写！");
                $("#graduate_subject").focus();
                return false;
            }else if( graduate_subject.size > 20 ){
                alert("本科院系长度过大！");
                $("#graduate_subject").focus();
                return false;
            }else if ( !graduate_college ){
                alert("本科学科门类未选择！");
                $("#graduate_college").focus();
                return false;
            }else if ( !graduate_professional_class ){
                alert("本科专业类未选择！");
                $("#graduate_professional_class").focus();
                return false;
            }else if( !graduate_profession ){
                alert("本科专业未选择！");
                $("#graduate_profession").focus();
                return false;
            }else if( !pro_stu_num ){
                alert("本专业同年级人数未填写！");
                $("#pro_stu_num").focus();
                return false;
            }else if( !ranking ){
                alert("本专业排名未填写！");
                $("#ranking").focus();
                return false;
            }else if( parseInt(ranking) > parseInt(pro_stu_num) ){
                alert("本专业排名大于本专业同年级人数，不合法！");
                $("#pro_stu_num").focus();
                $("#ranking").focus();
                return false;
            }else if( !grade_point ){
                alert("本科绩点未填写！");
                $("#grade_point").focus();
                return false;
            }else if( value_cet6 > 750){
                alert("英语六级成绩超出750分，不合法！");
                $("#value_cet6").focus();
                return false;
            }else if( !target_college ){
                alert("目标院系未选择！");
                $("#target_college").focus();
                return false;
            }else if( !target_subject ){
                alert("目标专业未选择！");
                $("#target_subject").focus();
                return false;
            }else if( !target_profession ){
                alert("目标方向未选择！");
                $("#target_profession").focus();
                return false;
            }else if( !target_professor ){
                alert("意向导师一志愿未选择！");
                $("#target_professor").focus();
                return false;
            }else if( !foreign_language ){
                alert("外语语种未选择！");
                $("#foreign_language").focus();
                return false;
            }else
            {
                $(this).prop("type","submit");
            }
        })

        // $("#addproject").click(function () {
        //     var certificate = document.getElementById("certificate").files[0];
        //     var file = $("#certificate").val;
        //     // alert(file+ '/' +certificate.name + '/' + certificate.type + '/' + certificate.size);
        //     // if(certificate.size){
        //     //
        //     // }
        //     alert(certificate.size/1024);
        //
        //     if(!file){
        //         $("#certificate").focus();
        //     }
        //     else if(certificate.size/1024 >2000) {
        //         $("#certificate").focus();
        //         alert("获奖凭证超出2M!");
        //     }else{
        //         $(this).prop("type","submit");
        //     }
        //
        // })
    });


</script>