<?php
    $title = '推免生注册补充信息';
    $this->headTitle($title);
?>
<!--<h3><?php echo $this->escapeHtml($title);?></h3>-->
<style type="text/css">
    .message{
        color: #b23131;
    }
</style>
<!--  提交审核按钮 -->
<br><br>
<div class='message'>
    提示1. 请在补充完个人全部信息【基本信息(含必填项)、科研经历(选填)、个人奖励含优秀营员(选填)、文件凭证(含必须上传的项)】后再提交审核。<br/>
    提示2. 在提交审核之前，您的所填信息可随意更改。<br/>
    提示3. 请在要求的提交审核期限内提交。<br/>
    <br/>
</div>
<?php
if(in_array(1,$this->rid)){
    echo " <a href = '".$this->url("stu/default",array("controller"=>"addinfo","action"=>"stuConfirmcheck"))."' onclick='javascript:return ifCheck()' class='btn btn-danger'>提交审核</a>";
}
?>
<br/>
<!--<input id="confirmcheck" type="button" onclick="javascript:return ifCheck()" class="btn" value=" 提交审核 ">-->
<!---<a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"stuConfirmcheck")); ?>' onclick='javascript:return ifCheck()' class='btn btn-danger'>提交审核</a>
<br/><br/>
----->
<ul class = "nav nav-tabs" id = "myTab" >
    <li> <a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfo","uid" => $this->uid)); ?>'>基本信息</a></li>
    <li class="active"><a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfoProject","uid" => $this->uid)); ?>'>科研经历</a></li>
    <li><a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfoHonour","uid" => $this->uid)); ?>' > 个人奖励（含优秀营员） </a></li>
    <li><a href = '<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"addInfoFile","uid" => $this->uid)); ?>'> 文件凭证 </a></li>
</ul>
<br>
<!--<div class = "tab-content" >-->
    <!-- ******************** Tab2 科研经历 ******************** -->
    <div class = "tab-pane active" id = "addinfo2" >
        <!--<h3>添加科研或实践项目经历</h3>-->
        <form class="form-horizontal"  action="/stu/addinfo/addInfoProject/uid/<?php echo $this->uid?>" method="post" enctype="multipart/form-data">
            <div class="control-group">
                <label class="control-label" for="project_name">项目名称</label>
                <div class = "controls">
                    <!--<input type="text" id="project_name" />-->
                    <textarea   rows="1" id="project_name" name="project_name" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
                    <div class='text-right'>
                        <em style='color:red'>50</em>/<span>50</span>字符
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="abstract">项目概要 </label>
                <div class = "controls">
                    <textarea class="form-control" rows="3" id="abstract" name="abstract" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
                    <div class='text-right'>
                        <em style='color:red'>255</em>/<span>255</span>字符
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="conclusion">项目结论 </label>
                <div class = "controls">
                    <textarea class="form-control" rows="2" id="conclusion" name="conclusion" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
                    <div class='text-right'>
                        <em style='color:red'>64</em>/<span>64</span>字符
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="achievement">项目成果 </label>
                <div class = "controls">
                    <textarea class="form-control" rows="3" id="achievement" name="achievement" onkeyup='textAreaChange(this)' onkeydown='textAreaChange(this)' onchange='textAreaChange(this)'></textarea>
                    <div class='text-right'>
                        <em style='color:red'>255</em>/<span>255</span>字符
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="certificate">获奖凭证（选填）</label>
                <div class = "controls">
                    <input type="file" id="certificate" name="certificate"  accept=".png,.jpeg,image/png, image/jpeg, image/jpg"/><span style='color:red'>（格式仅限jpg,jpeg,png，文件大小不能超过2M） </span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="certificate_level">项目级别 </label>
                <div class="controls">
                    <select id="certificate_level" name="certificate_level" class="active">
                        <option value=''>-请选择-</option>
                        <option value='1'>国家级</option>
                        <option value='2'>省市级</option>
                        <option value='3'>其他</option>
                    </select>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="button" id="add_project" class="btn btn-primary"> 添加科研或实践项目经历 </button>
                </div>
            </div>
        </form>


        <div class="span12">
            <?php if($this->project_table){
            ?>
            <h3>已提交的项目</h3>
            <table class='table table-striped table-hover table-condensed'>
                <thead>
                <th>项目名称</th>
                <th>概述</th>
                <th>研究结论</th>
                <th>成果</th>
                <th>获奖凭证</th>
                <th>获奖等级</th>
                <th>创建时间</th>
                <th>操作</th>
                </thead>
                <tbody>
                <?php
                        foreach ($this->project_table as $key => $row) {
                ?>
                <tr>

                    <td class="span2"> <?php echo $row->project_name;?></td>
                    <td class="span3"> <?php echo $row->abstract;?></td>
                    <td class="span3"> <?php echo $row->conclusion;?></td>
                    <td class="span3"> <?php echo $row->achievement;?></td>
                    <td  class="span6">
                        <?php if($row->certificate){
                            $image_url = substr($row->certificate,6);
                        ?>
                         <!--height="220" width="150"-->
                        <img src='<?php echo $this->basePath($image_url); ?>' alt="certificate" />
                        <?php } ?>
                    </td>
                    <td  class="span2"><?php echo $row->certificate_level;?></td>
                    <td  class="span2"><?php echo $row->create_at;?></td>
                    <td  class="span2">
                        <!--<?php echo $row->project_id;?>-->
                        <a href='<?php echo $this->url("stu/default",array("controller"=>"addinfo","action"=>"deleteProject","id"=>$row->project_id)); ?>'  onclick='javascript:return ifCheckdel()' class="button">删除  </a>
                    </td>
                </tr>
                <?php } ?> <!-- 循环输出项目记录-->
                </tbody>
            </table>
            <?php  } ?>
        </div>


    </div>
<!--</div>-->
<script type="text/javascript" src="<?php echo $this->basePath('js/stu/stuconfirm.js?version=1.1.1');?>"></script>
<script>

    /*
    *显示限制textarea输入字符数目
    */
    function textAreaChange(obj) {
        var $this = $(obj);
        var count_total = $this.next().children('span').text();
        var count_input = $this.next().children('em');
        var area_val = $this.val();
        if(area_val.len()>count_total){
            area_val = autoAddEllipsis(area_val,count_total);//根据字节截内容
            $this.val(area_val);
            count_input.text(0);//显示可输入数
        }else{
            count_input.text(count_total - area_val.len());//显示可输入数
        }
    }
    /*
     * 得到字符串的字节长度
     */
    String.prototype.len = function(){
        return this.replace(/[^\x00-\xff]/g, "xx").length;
    };
    /*
     * 处理过长的字符串，截取并添加省略号
     * 注：半角长度为1，全角长度为2
     * pStr:字符串
     * pLen:截取长度
     * return: 截取后的字符串
     */
    function autoAddEllipsis(pStr, pLen) {
        var _ret = cutString(pStr, pLen);
        var _cutFlag = _ret.cutflag;
        var _cutStringn = _ret.cutstring;
        return _cutStringn;
    }
    /*
    * 取得指定长度的字符串
    * 注：半角长度为1，全角长度为2
    * pStr:字符串
    * pLen:截取长度
    * return: 截取后的字符串
    */
    function cutString(pStr, pLen) {
        // 原字符串长度
        var _strLen = pStr.length;
        var _tmpCode;
        var _cutString;
        // 默认情况下，返回的字符串是原字符串的一部分
        var _cutFlag = "1";
        var _lenCount = 0;
        var _ret = false;
        if (_strLen <= pLen/2){_cutString = pStr;_ret = true;}
        if (!_ret){
            for (var i = 0; i < _strLen ; i++ ){
                if (isFull(pStr.charAt(i))){_lenCount += 2;}
                else {_lenCount += 1;}
                if (_lenCount > pLen){_cutString = pStr.substring(0, i);_ret = true;break;}
                else if(_lenCount == pLen){_cutString = pStr.substring(0, i + 1);_ret = true;break;}
            }
        }
        if (!_ret){_cutString = pStr;_ret = true;}
        if (_cutString.length == _strLen){_cutFlag = "0";}
        return {"cutstring":_cutString, "cutflag":_cutFlag};
    }
    /*
     * 判断是否为全角
     *
     * pChar:长度为1的字符串
     * return: true:全角
     *         false:半角
     */
    function isFull (pChar){
        if((pChar.charCodeAt(0) > 128)){return true;}
        else{return false;}
    }


    $(document).ready(function(){

        $("#add_project").click(function () {
            var project_name = $("#project_name").val();
            var abstract = $("#abstract").val();
            var conclusion = $("#conclusion").val();
            var achievement = $("#achievement").val();
            var file = $("#certificate").val();
            var certificate_level = $("#certificate_level").val();
            // alert(file+ '/' +certificate.name + '/' + certificate.type + '/' + certificate.size);
            if(!project_name){
                alert("项目名称不可以为空！");
                $("#project_name").focus();
            } else if(!abstract){
                alert("项目概要不可以为空！");
                $("#abstract").focus();
            }else if(!conclusion){
                alert("项目结论不可以为空！");
                $("#conclusion").focus();
            }else if(!achievement){
                alert("项目成果不可以为空！");
                $("#achievement").focus();
            }else if(!certificate_level){
                alert("请选择项目级别！");
                $("#certificate_level").focus();
            }else if(file){
                var typeAllow = ["jpg","jpeg","png"];//允许的后缀
                var certificate = document.getElementById("certificate").files[0];
                var certificatetype = (certificate.name.substring(certificate.name.lastIndexOf(".")+1,certificate.name.length)).toLowerCase(); // 判断文件类型是否在要求的里面
                if(certificate.size/1024 >2000){//如果上传了文件，就判断大小
                    $("#certificate").focus();
                    alert("获奖凭证超出2M!");
                }
                else if($.inArray(certificatetype,typeAllow) < 0){
                    $("#certificate").focus();
                    alert(certificate.name + " 的文件后缀不符合该文件凭证上传格式！请重新上传!");
                    return false;
                }
                else{
                    $(this).prop("type","submit");
                }
            }else{
                $(this).prop("type","submit");
            }
        })
    });

</script>