<style>
    h4{
        margin:0 auto;
    }
    #sum{
        font-size: 20px;
    }
    .table-striped{
        width: 50%;
    }
    #none{
        font-size: 20px;
        margin-top: 20px;
    }
</style>

<?php
if($this->flag == 1)
{
    $female = 0;
    $male = 0;
    foreach($this->gender as $x=>$x_value)
    {
        foreach ($x_value as $key => $value) {
            if($value == '1')
                $female++;
            else
                $male++;
        }
    }
    $good = 0;
    $total = 0;
    foreach($this->isTwo as $x=>$x_value)
    {
        foreach ($x_value as $key => $value) {
            $good++;
        }
    }
    foreach($this->allResult as $x=>$x_value)
    {
        foreach ($x_value as $key => $value) {
            $total++;
        }
    }
    if($total == 0)
    {
        echo "<p id = 'sum'>".$this->range."当前无人报考</p>";
    }
    else{
        echo "<p id = 'sum'>".$this->range."学生总人数".$total."，其中985/211总人数".$good."。</p><br>";
        echo "<p id = 'sum'>".$this->range."女性人数".$female."，".$this->range."男性人数".$male."。</p><br>";
        echo "<h4>".$this->range."生源大学排序</h4>";
        echo "<table class='table table-striped'><thead>";
        foreach ($this->column as $key => $value) {
            echo "<th/>".$value."</th>";
        }
        echo "</thead>";
        foreach ($this->UniRank as $key_name => $row) {
            echo "<tr>";
            foreach ($row as $key => $value) {
                echo "<td>".$row[$key]."</td>";
            }
            echo "</tr>";
        }
        echo "</table>";
    }

}
else if($this->flag == 2)
{
    for($i = 0;$i < $this->num; $i++)
    {
        $female = 0;
        $male = 0;
        foreach($this->gender[$i] as $x=>$x_value)
        {
            foreach ($x_value as $key => $value) {
                if($value == '1')
                    $female++;
                else
                    $male++;
            }
        }
        $good = 0;
        $total = 0;
        foreach($this->isTwo[$i] as $x=>$x_value)
        {
            foreach ($x_value as $key => $value) {
                $good++;
            }
        }
        foreach($this->allResult[$i] as $x=>$x_value)
        {
            foreach ($x_value as $key => $value) {
                $total++;
            }
        }
        echo "<p id = 'sum'>".$total."</p>";
        if($total == 0)
        {
            echo "<p id = 'sum'>".$this->range[$i][0]["team_name"]."当前无人报考</p>";
        }
        else{
            echo "<p id = 'sum'>".$this->range[$i][0]["team_name"]."学生总人数".$total."，其中985/211总人数".$good."。</p><br>";
            echo "<p id = 'sum'>".$this->range[$i][0]["team_name"]."女性人数".$female."，".$this->range[$i][0] ["team_name"]."男性人数".$male."。</p><br>";
            echo "<h4>".$this->range[$i][0]["team_name"]."生源大学排序</h4>";
            echo "<table class='table table-striped'><thead>";
            foreach ($this->column as $key => $value) {
                echo "<th/>".$value."</th>";
            }
            echo "</thead>";
            foreach ($this->UniRank[$i] as $key_name => $row) {
                echo "<tr>";
                foreach ($row as $key => $value) {
                    echo "<td>".$row[$key]."</td>";
                }
                echo "</tr>";
            }
            echo "</table>";
        }
    }
}
else if($this->flag == 0)
{
    echo "<p id='none'>您目前尚未负责任何学院或小组，请确认后再次登陆!!!</p>";
}




