<style>
    h4{
        margin:0 auto;
    }
    p{
        font-size: 20px;
    }
</style>

<?php
if($this->flag == 1)
{
    $female = 0;
    $male = 0;
    foreach($this->gender as $x=>$x_value)
    {
        foreach ($x_value as $key => $value) {
            if($value == '1')
                $female++;
            else
                $male++;
        }
    }
    echo "<p>".$this->range."女性人数".$female."，".$this->range."男性人数".$male."。</p><br>";
    $good = 0;
    $total = 0;
    foreach($this->isTwo as $x=>$x_value)
    {
        foreach ($x_value as $key => $value) {
            $good++;
        }
    }
    foreach($this->allResult as $x=>$x_value)
    {
        foreach ($x_value as $key => $value) {
            $total++;
        }
    }
    echo "<p>".$this->range."学生总人数".$total."，其中985/211总人数".$good."。</p><br>";
    echo "<h4>".$this->range."生源大学排序</h4>";
    echo "<table class='table table-striped'><thead>";
    foreach ($this->column as $key => $value) {
        echo "<th/>".$value."</th>";
    }
    echo "</thead>";
    foreach ($this->UniRank as $key_name => $row) {
        echo "<tr>";
        foreach ($row as $key => $value) {
            echo "<td>".$row[$key]."</td></tr>";
        }
    }
    echo "</table>";
}
else if($this->flag == 2)
{
    for($i = 0;$i < $this->num; $i++)
    {
        $female = 0;
        $male = 0;
        foreach($this->gender[$i] as $x=>$x_value)
        {
            foreach ($x_value as $key => $value) {
                if($value == '1')
                    $female++;
                else
                    $male++;
            }
        }
        echo "<p>".$this->range[$i]."女性人数".$female."，".$this->range[$i]."男性人数".$male."。</p><br>";
        $good = 0;
        $total = 0;
        foreach($this->isTwo[$i] as $x=>$x_value)
        {
            foreach ($x_value as $key => $value) {
                $good++;
            }
        }
        foreach($this->allResult[$i] as $x=>$x_value)
        {
            foreach ($x_value as $key => $value) {
                $total++;
            }
        }
        echo "<p>".$this->range[$i]."学生总人数".$total."，其中985/211总人数".$good."。</p><br>";
        echo "<h4>".$this->range[$i]."生源大学排序</h4>";
        echo "<table class='table table-striped'><thead>";
        foreach ($this->column as $key => $value) {
            echo "<th/>".$value."</th>";
        }
        echo "</thead>";
        foreach ($this->UniRank[$i] as $key_name => $row) {
            echo "<tr>";
            foreach ($row as $key => $value) {
                echo "<td>".$row[$key]."</td></tr>";
            }
        }
        echo "</table>";
    }
}




