<?php

$title = '修改密码';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title);?></h1>

<?php
$form=$this->form;
$form->setAttribute('action',$this->url('manage/default',array("controller"=>"Account",'action'=>'alterPassword')));
$form->setAttribute('method', 'POST');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('uid'));
echo $this->formRow($form->get('password1'))."<br/>";       //邮箱
echo $this->formRow($form->get('password2'))."<br/>";
echo $this->formRow($form->get('password3'))."<br/>";
echo "<br/>";
echo "<br/>";
echo $this->formSubmit($form->get('submit')); 			//提交
echo $this->form()->closeTag();
?>