<!--<input name="myInput" type="file"  /><br />-->
<!--<input name="myInput" type="file"  /><br />-->
<!--<input name="myInput" type="file"  /><br />-->
<!--<br />-->
<!--<button type="button" onclick="getElements()"  value="How many input elements?" >submit</button>-->

<!--<script type="text/javascript">-->
    <!--function getElements()-->
    <!--{-->
        <!--var num = $("input:file").length;-->
        <!--// var num = $('input[type="file"]').length;-->
        <!--// var num = $('input:file').length;-->
        <!--// alert(num);-->
        <!--// alert('111');-->
        <!--var x = document.getElementsByTagName("input");-->

        <!--// var x = $("input:file");-->
        <!--// document.getElementsByTagName('input')[0]-->
        <!--for (var i = 0 ; i < num ; i++) {-->
            <!--if(x[i].files[0]){-->
                <!--// alert(x[i].files[0].size);-->
            <!--}-->

        <!--}-->

    <!--}-->
<!--</script>-->