<style>
    label span,label{
        width:150px;
        text-align: right;
        margin-right: 10px;
        height: 35px;
    }
    input[type="text"]{
        height: 30px;
        margin-bottom: 0;
    }
    .message{
        color: #b23131;
    }
    .message1{
        color: red;
        font-size: 150%;
    }
    .message2{
        color: red;
    }
    .gender{
        width: 50px;
    }
</style>

<?php
    $title = '推免生注册';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title);?></h3>

<h5>个人基本信息(注册后本页面内容不可修改)</h5>
<fieldset>
    <span class='message'>1.点击验证邮箱，登录邮箱查看yzbmail@bjfu.edu.cn发送的验证邮件，点击链接对邮箱进行激活。</span><br/>
    <span class='message'>2.请慎重填写邮箱，此邮箱将作为登录账号以及后续发送通知的主要联系方式。</span><br/>
    <span class='message'>3.提示邮箱已激活，无需重复激活。页面无需刷新，请继续进行注册。</span><br/>
    <span class='message'>4.提交信息成功后，请使用电子邮箱作为用户名，身份证号作为初始密码登录本系统，进一步补充资料。</span><br/>
    <span class='message'>5.如有任何问题，请将问题详细描述、截图并发送邮件至yzbmail@bjfu.edu.cn。</span><br/>
    <span class='message'>6.标星号为必填项。</span><br/>
    <span class='message'>7.每人只允许注册一个账号，多余账号则由管理员删除。</span><br/>
    <span class='message'>8.本科高校中不存在的大学即没有推免资格。若有问题，请联系管理员咨询或添加。</span><br/>
    <span class='message'>9.若为经校研究生招生小组审定的高水平运动员或本科为外语专业/小语种的同学，请在“英语四级成绩”处填写0，登录系统后在“‘个人信息管理’->‘填写个人补充信息’->‘文件凭证’”的“英语四级成绩单”处上传上传相应的英语四级考试合格证书或该语种国内公共外语相当于英语四级考试合格证书。</span><br/>
</fieldset>
<br/>
<div id="stuinfo">
    <?php
    $form->setAttribute('action',$this->url('stu/default',array('controller'=>'register','action'=>'register')));
    $form->setAttribute('method', 'POST');
    $form->prepare();
    echo $this->form()->openTag($form);

    ?>
    <!-- 1.1 申请类型-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('apply_type')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('apply_type')); ?></div>
        <!--<?php echo $this->formElementErrors($form->get('apply_type')); ?>-->
        <!--<?php echo $this->formRow($form->get('apply_type')); ?>-->
    </div>
    <br>
    <!-- 1.2 姓名-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('user_name'));?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('user_name'));?></div>
        <!--<?php echo $this->formElementErrors($form->get('user_name'));?>-->
    </div>
    <br>
    <!-- 1.3 性别-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('gender')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('gender')); ?></div>
        <!--<?php echo $this->formElementErrors($form->get('gender')); ?>-->
    </div>
    <br>
    <!-- 1.4 身份证号-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('idcard')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('idcard')); ?></div>
        <!--<?php echo $this->formElementErrors($form->get('idcard')); ?>-->
    </div>
    <br>
    <!-- 1.5 民族-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('nationality')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('nationality')); ?></div>
        <!--<?php echo $this->formElementErrors($form->get('nationality')); ?>-->
    </div>
    <br>
    <!-- 1.6 政治面貌-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('political_status'));?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('political_status'));	?></div>
        <!--<?php echo $this->formElementErrors($form->get('political_status'));	?>-->
    </div>
    <br/>
    <!-- 1.7 联系方式-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('phone')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('phone')); ?></div>
        <!--<?php echo $this->formElementErrors($form->get('phone')); ?>-->
    </div>
    <br/>
    <!-- 1.8 电子邮件-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('email'));?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span>
            <?php echo $this->formElement($form->get('email'));?>&nbsp&nbsp&nbsp
            <!--<?php echo $this->formElementErrors($form->get('email'));?>-->
            <input type='button' class='btn btn-info' id='mailbutton' value='验证邮箱'/>
        </div>
    </div>
    <div class="row">
        <div class="span5" style="margin-left: 2px;"></div> <div class='emailstatus'></div>
    </div>
    <br/>

    <!-- 1.9 本科高校-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('graduate_university')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span>
            <?php echo $this->formElement($form->get('graduate_university_province')); ?>
            <?php echo $this->formElement($form->get('graduate_university')); ?>
            <!--<?php echo $this->formElementErrors($form->get('graduate_university')); ?>-->
        </div>
    </div>
    <br/>
    <!-- 1.10 CET4-->
    <div class="row">
        <div class="span3"><?php echo $this->formLabel($form->get('value_cet4')); ?></div>
        <div class="span7"><span class = 'message'>*&nbsp;</span><?php echo $this->formElement($form->get('value_cet4')); ?></div>
        <!--<?php echo $this->formElementErrors($form->get('value_cet4')); ?>-->
    </div>
    <br/>
    <div class="row">
        <div class="span4"></div>
        <?php echo $this->formSubmit($form->get('registersubmit'));  ?>
    </div>
    <?php echo $this->form()->closeTag();?>
    <hr>
    <!--  文件下载专区 -->
    <div class="row">
        <h5>文件下载专区</h5>
    </div>
    <div class="row">
        <a href='<?php echo $this->basePath("/download/申请直博生个人陈述表.doc");?>'  download="[直博生下载]申请直博生个人陈述表.doc">[直博生下载] 申请直博生个人陈述表.doc</a>
    </div>
    <div class="row">
        <a href='<?php echo $this->basePath("/download/直博生专家推荐信.doc");?>'  download="[直博生下载]直博生专家推荐信.doc">[直博生下载] 直博生专家推荐信.doc</a>
    </div>

</div>
<script type="text/javascript" src="<?php echo $this->basePath('js/stu/md5.js');?>"></script>
<script>
    function gra_selectuni(){
        var selected = this.value;
        $.ajax({
            type: 'GET',
            url: '/stu/register/selectUniByPid/select/'+selected,
            // data: {x:1,city:selected},
            dataType: 'json',
            success: function (json) {
                var str = "<option value=''>请选择学校</option>";
                for( var key in json.data ){
                    str += "<option value='" + key + "'>" + json.data[key] + "</option>";
                }
                // $("#graduate_university").html(str);
                var graduate_university = document.getElementById("graduate_university");
                graduate_university.innerHTML = str;
            },
            error:function () {
                // alert("111");
            }
        })

    }
    var graduate_university_province = document.getElementById("graduate_university_province");
    graduate_university_province.onchange = gra_selectuni;
</script>
<script>
    $(document).ready(function(){
        $("#registersubmit").click(function () {
            var apply_type = $("#apply_type").val();
            var user_name = $("#user_name").val();
            var gender = $("#gender").val();
            var idcard = $("#idcard").val();
            var nationality = $("#nationality").val();
            var political_status = $("#political_status").val();
            var phone = $("#phone").val();
            var email = $("#email").val();
            var graduate_university_province = $("#graduate_university_province").val();
            var graduate_university = $("#graduate_university").val();
            var value_cet4 = $("#value_cet4").val();

            var idcardreg = /(^\d{18}$)|(^\d{17}(\d|X|x)$)/;//身份证的模式匹配

            if(!apply_type){ //判空
                alert("请选择申请类型！");
                $("#apply_type").focus();
                return false;
            }else if(!user_name){
                alert("请填写姓名！");
                $("#user_name").focus();
                return false;
            }else if(!gender){
                alert("请选择性别！");
                $("#gender").focus();
                return false;
            }else if(!idcard){
                alert("请填写身份证号！");
                $("#idcard").focus();
                return false;
            }else if(!nationality){
                alert("请填写民族！");
                $("#nationality").focus();
                return false;
            }else if(!political_status){
                alert("请选择政治面貌！");
                $("#political_status").focus();
                return false;
            }else if(!phone){
                alert("请填写联系方式(！");
                $("#phone").focus();
                return false;
            }else if(!email){
                alert("请填写电子邮箱！");
                $("#email").focus();
                return false;
            }else if(!graduate_university_province){
                alert("请选择本科高校所在省份！");
                $("#graduate_university_province").focus();
                return false;
            }else if(!graduate_university){
                alert("请选择本科高校！");
                $("#graduate_university").focus();
                return false;
            }else if(!value_cet4){
                alert("请填写英语四级成绩！");
                $("#value_cet4").focus();
                return false;
            }else if(user_name.length>50){ //长短/模式匹配
                alert("姓名过长！请更改或联系管理员邮箱!");
                $("#user_name").focus();
                return false;
            }else if(nationality.length>64){
                alert("民族过长！请更改或联系管理员邮箱!");
                $("#nationality").focus();
                return false;
            }else if(idcardreg.test(idcard)=== false){
                alert("身份证号输入不合法");
                $("#idcard").focus();
                return false;
            }else if(phone.length!=11){
                alert("手机号码输入不合法！");
                $("#phone").focus();
                return false;
            }else if(value_cet4 < 425 && (value_cet4!=0)){
                alert("英语四级成绩未过425，不具备推免资格！");
                $("#value_cet4").focus();
                return false;
            }else if(value_cet4 > 750){
                alert("英语四级成绩超过750分，不合法！");
                $("#value_cet4").focus();
                return false;
            }
            else{
                // alert(user_name.length);
                // $(this).prop("type","submit");
            }
        }),
        $("#mailbutton").click(function (){
            // var mailbutton = this;
            var email = $("#email").val();// var email = document.getElementById("email").value;
            if(!email ){
                alert("电子邮箱(必填)尚未填写，不能进行邮箱验证！");
            }else {
                // alert(email);
                // var emailReg = /^\w+@(\w        emailbutton_limittime = function (mailbutton) {)+(\.\w+)+/;
                var emailReg = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
                if(emailReg.test(email)){//邮箱格式验证通过
                    emailbutton_limittime(this);
                    $.ajax({
                        type: 'GET',
                        url: '/stu/register/validatemail/mail/' + email, //查看邮箱是否注册，是否可以使用
                        // data:{email:email},
                        // enctype:"multipart/form-data",
                        dataType: 'json', //预期的服务器响应的数据类型。
                        success: function (result) {
                            // $('.emailstatus').html(result.data);
                            if(result.ifregisterEmail == 1)//邮箱已经被注册了
                            {
                                alert(result.data);
                                // $('.emailstatus').html(result.data);
                            }else if(result.ifregisterEmail == 0){//邮箱没被注册，发送邮箱
                                alert(result.data);
                                // $('.emailstatus').html(result.data);
                                // console.log(result.data);
                                if(result.ifactive == 0){
                                    var send_url = '<?php echo $this->mail_api;?>';
                                    // var protocol = window.location.protocol;
                                    var host = window.location.host;
                                    var post = window.location.port;
                                    if(post){
                                        var locationurl = host +":"+ post;
                                    }else{
                                        var locationurl = host ;
                                    }
                                    var encrypt = hex_md5(email);//对邮箱进行加密，形成链接的一部分
                                    // var encrypt = '<?php echo base64_encode(md5(' + email + '));?>' ;
                                    var url = 'http://'+locationurl+'/stu/register/activemail/active/'+encrypt;//激活邮箱的url
                                    // var content = '点击< a href="' +url+'">验证邮箱</ a>或手动访问'+url ;
                                    var content = '点击 <html><body><a href="' +url+'">验证邮箱</a></body></html> 或手动访问 '+url ;
                                    // var content = '手动访问'+url ;
                                    // alert(content);
                                    $.ajax({ //调用邮箱类
                                        type:"POST",
                                        url:send_url,
                                        // url:'/info/Mail/mailSendApi',
                                        crossDomain: true,
                                        data:{
                                            'receiver': email,
                                            'title' : '北京林业大学推免生系统邮箱验证',
                                            'content': content,
                                        },
                                        success:function(result){
                                            // 发送成功
                                            $('.emailstatus').html("发送成功！请前往登录您的邮箱进行激活");
                                        },
                                        error : function(XMLHttpRequest, textStatus, errorThrown){
                                            // 发送失败
                                            $('.emailstatus').html(XMLHttpRequest, textStatus, errorThrown);
                                        }
                                    });
                                }

                            }

                        },
                        error: function () {// console.log(XMLHttpRequest+textStatus+errorThrown);
                            alert("服务器未返回数据，可能服务器忙，请稍后重试");
                        },
                    });
                }else{
                    alert("电子邮箱(必填)格式错误，不能进行邮箱验证！");
                }
            }
        });
        var waittime = 60;//设置验证邮箱间隔时间为60s
        emailbutton_limittime = function (mailbutton) {
            if(waittime == 0){
                mailbutton.removeAttribute('disabled');
                mailbutton.value = "验证邮箱";
                waittime = 60;
            }else {
                mailbutton.setAttribute("disabled", "true");
                mailbutton.value = waittime + "秒后可重新验证邮箱";
                waittime--;
                setTimeout(function () {
                    emailbutton_limittime(mailbutton)
                },1000)
            }
        }

    });
</script>