<h3>系统配置</h3>

<span style='color: red; font-size: medium;'>提示:本界面为设置系统的基本配置信息，可不做更改。<br></b></span>
<table class="table table-striped">
    <thead>
    <?php
    foreach ($column as $key => $value) {
        echo "<th/>".$value."</th>";
    }
    ?>
    </thead>
    <?php
    foreach ($setting as $key_name => $row) {
        ?><tr><?php
        foreach ($column as $key => $value) {
            if($key == 'key_value'){
                echo "<td id=".$row['id'].">".$row[$key]."</td>";
                continue;
            }
            if($key == 'operation'){
                ?><td/><?php
                echo "<button class='btn btn-primary' id='edit-".$row["id"]."' onclick='edit(".$row['id'].",\"".$row['key_value']."\")'>编辑</button>";
                ?></td><?php
                continue;
            }
            echo "<td>".$row[$key]."</td>";
        }
        ?></tr><?php
    }
    ?>
</table>
<div>
    <form id="upload-form" action="/manage/setting/uploadLogo" method="post" enctype="multipart/form-data" >
        上传学校校徽图片：  　　　<input type="file" id="upload" name="upload" />
        　　　<input type="submit" value="上传图片"  class="btn-primary" />
    </form>
</div>

<script src="/js/manage/config.js"></script>